# Generated by Django 3.1.6 on 2021-05-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=12)),
                ('cpassword', models.CharField(max_length=12)),
                ('accept', models.CharField(blank=True, choices=[('accept', 'Accept'), ('deny', 'Deby')], max_length=10, null=True)),
            ],
        ),
    ]
