# Generated by Django 3.1.6 on 2021-05-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
